apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd-applicationset-controller
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  project: cluster-addons
  syncPolicy:
    automated: {}
  destination:
    namespace: {{ .Values.spec.apps.argoProjectConfig.destination.namespace }}
    server: {{ .Values.spec.apps.argoProjectConfig.destination.server }}
  source:
    path: cluster-addons/argocd-applicatonset
    repoURL: https://github.com/sandile-yakka/argo-cluster-addons-explorer
    targetRevision: master