apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecr-cred-renew
  namespace: argo-cd
spec:
  project: cluster-addons
  syncPolicy:
    automated: {}
  destination:
    namespace: {{ .Values.spec.destination.namespace }}
    server: {{ .Values.spec.destination.server }}
  source:
    path: cluster-addons/ecr-renew
    repoURL: https://github.com/sandile-yakka/argo-cluster-addons
    targetRevision: master