{{ if .Values.spec.apps.ecrCredRenew.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name:   
  namespace: argo-cd
spec:
  project: cluster-addons
  ignoreDifferences: 
  - group: ""
    kind: Secret
    jsonPointers:
      - /data
  syncPolicy:
    automated: {}
  destination:
    namespace: {{ .Values.spec.apps.ecrCredRenew.destination.namespace }}
    server: {{ .Values.spec.apps.ecrCredRenew.destination.server }}
  source:
    path: cluster-addons/ecr-renew
    repoURL: https://github.com/sandile-yakka/argo-cluster-addons-explorer
    targetRevision: master
{{ end }}