apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-explorer-app-of-apps
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: cluster-addons
  syncPolicy:
    automated: {}
  destination:
    namespace: argo-cd
    server: https://kubernetes.default.svc
  source:
    path: cluster-app-of-apps
    repoURL: https://github.com/sandile-yakka/argo-cluster-addons-explorer
    targetRevision: master