apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "basic-mutating-webhook.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 443
      protocol: TCP
      name: http
  selector:
    {{- include "basic-mutating-webhook.selectorLabels" . | nindent 4 }}
