namespace: argo-events
spec:
  apps:
    verticalPodAutoscaler:
      enabled: true
      destination:
        namespace: kube-system
        server: https://kubernetes.default.svc
    ecrCredRenew:
      enabled: true
      destination:
        namespace: argo-events
        server: https://kubernetes.default.svc
    argoProjectConfig:
      enabled: false
      destination:
        namespace: argo-events
        server: https://kubernetes.default.svc
    argocdApplicationset:
      enabled: true
      destination:
        namespace: argo-cd
        server: https://kubernetes.default.svc
    mutatingWebhook:
      enabled: true
      destination:  
        namespace: default
        server: https://kubernetes.default.svc

