# Default values for basic-mutating-webhook.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: sandile11/basic-mutating-webhook
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v2.0.1"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  annotations: {}
podAnnotations: {}
podSecurityContext: {}
securityContext:
  runAsUser: 1000
service:
  type: ClusterIP
  port: 443
resources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
webhook: # Mutating webhook configuration
  namespace: default # The namespace whose deployments the webhook will intercepts
nodeSelector: {}

tolerations: []

affinity: {}
