apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hamster-vpa-test-dev
  namespace: argo-cd
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: dev-services
  syncPolicy:
    automated: {}
  source:
    path: dev/hamster-vpa-test
    repoURL: https://github.com/sandile-yakka/argo-cluster-addons-explorer
    targetRevision: master
