annotations:
  artifacthub.io/changes: |
    - "[Added]: Install the chart into a kind cluster during the chart testing process"
    - "[Changed]: Parameter 'args.namespace' now defaults to the namespace where you install the chart to"
apiVersion: v2
appVersion: v0.2.0
description: A Helm chart for installing ArgoCD ApplicationSet
home: https://github.com/argoproj/argo-helm
icon: https://argocd-applicationset.readthedocs.io/en/stable/assets/logo.png
keywords:
- argoproj
- appset
- gitops
maintainers:
- name: maruina
name: argocd-applicationset
type: application
version: 1.6.0
