apiVersion: v2
appVersion: 0.9.2
dependencies:
- name: common
  repository: https://charts.bitnami.com/bitnami/
  version: 1.7.1
description: Set of components that automatically adjust the amount of CPU and memory
  requested by pods running in the Kubernetes Cluster
home: https://github.com/kubernetes/autoscaler
maintainers:
- email: sebastien.prudhomme@gmail.com
  name: sebastien-prudhomme
name: vertical-pod-autoscaler
version: 3.5.0
