kubeVersion: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

commonAnnotations: {}

commonLabels: {}

admissionController:
  replicaCount: 1

  image:
    repository: k8s.gcr.io/autoscaling/vpa-admission-controller
    tag: 0.9.2
    pullPolicy: IfNotPresent

  pdb:
    create: false
    minAvailable: 1

  serviceAccount:
    create: true
    annotations: {}
    name:

  podAnnotations: {}

  podLabels: {}

  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 65534

  securityContext: {}

  livenessProbe:
    enabled: true
    initialDelaySeconds: 0
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 3
    successThreshold: 1

  readinessProbe:
    enabled: true
    initialDelaySeconds: 0
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 3
    successThreshold: 1

  service:
    annotations: {}
    type: ClusterIP

  resources: {}

  nodeSelector: {}

  tolerations: []

  affinity: {}

  extraArgs:
    v: 2
    # vpa-object-namespace: ""
    # webhook-timeout-seconds: 30

  # Additional container environment variables
  extraEnvVars: []
  #  - name: MY-NAME
  #    value: "MY-VALUE"

  # Name of existing ConfigMap containing additional container environment variables
  extraEnvVarsCM:

  # Name of existing Secret containing additional container environment variables
  extraEnvVarsSecret:

  metrics:
    service:
      annotations: {}
      type: ClusterIP
      # Metrics service port
      port: 8944
  tls:
    caCert: ""
    cert: ""
    key: ""
    existingSecret: ""

recommender:
  replicaCount: 1

  image:
    repository: k8s.gcr.io/autoscaling/vpa-recommender
    tag: 0.9.2
    pullPolicy: IfNotPresent

  pdb:
    create: false
    minAvailable: 1

  serviceAccount:
    create: true
    annotations: {}
    name:

  podAnnotations: {}

  podLabels: {}

  podSecurityContext:
    # fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 65534

  securityContext: {}

  livenessProbe:
    enabled: true
    initialDelaySeconds: 0
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 3
    successThreshold: 1

  readinessProbe:
    enabled: true
    initialDelaySeconds: 0
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 3
    successThreshold: 1

  resources: {}

  nodeSelector: {}

  tolerations: []

  affinity: {}

  extraArgs:
    # checkpoints-gc-interval: 10m0s
    # checkpoints-timeout: 1m0s
    # cpu-histogram-decay-half-life: 24h0m0s
    # container-name-label: name
    # container-namespace-label: namespace
    # container-pod-name-label: pod_name
    # history-length: 8d
    # history-resolution: 1h
    # kube-api-burst: 10
    # kube-api-qps: 5
    # memory-aggregation-interval: 24h0m0s
    # memory-aggregation-interval-count: 8
    # memory-histogram-decay-half-life: 24h0m0s
    # memory-saver: false
    # metric-for-pod-labels: up{job="kubernetes-pods"}
    # min-checkpoints: 10
    # pod-label-prefix: pod_label_
    # pod-name-label: kubernetes_pod_name
    # pod-namespace-label: kubernetes_namespace
    # pod-recommendation-min-cpu-millicores: 25
    # pod-recommendation-min-memory-mb: 250
    # prometheus-address: ""
    # prometheus-cadvisor-job-name: kubernetes-cadvisor
    # prometheus-query-timeout: 5m
    # recommendation-margin-fraction: 0.15
    # recommender-interval: 1m0s
    # storage: checkpoint
    v: 2
    # vpa-object-namespace: ""

  # Additional container environment variables
  extraEnvVars: []
  #  - name: MY-NAME
  #    value: "MY-VALUE"

  extraEnvVarsCM:

  extraEnvVarsSecret:

  metrics:
    service:
      annotations: {}

      type: ClusterIP
      port: 8942

updater:
  replicaCount: 1

  image:
    repository: k8s.gcr.io/autoscaling/vpa-updater
    tag: 0.9.2
    pullPolicy: IfNotPresent

  pdb:
    create: false
    minAvailable: 1

  serviceAccount:
    create: true
    annotations: {}
    name:

  podAnnotations: {}

  podLabels: {}

  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 65534

  securityContext: {}

  livenessProbe:
    enabled: true
    initialDelaySeconds: 0
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 3
    successThreshold: 1

  readinessProbe:
    enabled: true

    initialDelaySeconds: 0

    periodSeconds: 10

    timeoutSeconds: 1

    failureThreshold: 3

    successThreshold: 1

  resources: {}

  nodeSelector: {}

  tolerations: []

  affinity: {}

  extraArgs:
    # evict-after-oom-threshold: 10m0s
    # eviction-rate-burst: 1
    # eviction-rate-limit: -1
    # eviction-tolerance: 0.5
    # min-replicas: 2
    # updater-interval: 1m0s
    # use-admission-controller-status: true
    v: 2
    # vpa-object-namespace: ""

  # Additional container environment variables
  extraEnvVars: []
  #  - name: MY-NAME
  #    value: "MY-VALUE"

  extraEnvVarsCM:

  extraEnvVarsSecret:

  metrics:
    service:
      # Metrics service annotations
      annotations: {}

      # Metrics service type
      type: ClusterIP

      # Metrics static cluster IP address or None for headless service when service type is ClusterIP
      # clusterIP: 10.43.0.100

      # Metrics service port
      port: 8943
