annotations:
  artifacthub.io/changes: |
    - "[Added]: Additional manifests to deploy within the chart"
apiVersion: v2
appVersion: v3.4.0
description: A Helm chart for Argo Workflows
home: https://github.com/argoproj/argo-helm
icon: https://raw.githubusercontent.com/argoproj/argo-workflows/master/docs/assets/argo.png
maintainers:
- name: argoproj
  url: https://argoproj.github.io/
name: argo-workflows
sources:
- https://github.com/argoproj/argo-workflows
type: application
version: 0.20.0
